### ISSUE TITLE
我想开发个修改昵称功能，请问可以实现吗？怎么实现？

### ISSUE THREAD

**Issue by zhong-wx** [opq-osc/OPQBot#15]

**Comment by mcoo** [comment]
可以实现修改群昵称 
https://github.com/opq-osc/OPQBot/blob/main/main.go#L761
```golang
func (b *BotManager) SetGroupNewNick(newNick string, groupID, userId int64) error {
```

**Comment by zhong-wx** [comment]
OPQUrl 这个参数是怎么获取的呢？

**Comment by mcoo** [comment]
你需要搭建一个`OPQ`的程序
https://github.com/opq-osc/OPQ/wiki/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97
下载地址为：https://github.com/opq-osc/OPQ/releases/tag/v6.0.20
`OPQUrl`就是你搭建好的程序开放的地址，例如`http://127.0.0.1:8888`

**Comment by mcoo** [comment]
暂时先关闭如果有问题请打开
