### ISSUE TITLE
怎么用这个qzone包呢

### ISSUE THREAD

**Issue by James4Ever0** [opq-osc/OPQBot#21]
我尝试用gopy来链接OPQBot 但是只能启动OPQBot包里面的方法 qzone没法调用

我尝试运行例子 但是例子里面并没有说怎么import qzone

我用gopy分别编译OPQBot和OPTBot/qzone  同时import 但是出现了segmentation error

**Comment by James4Ever0** [comment]
好像可以了 自己又改了点代码

```bash
go mod init dummy.com/dum
PKGNAME=github.com/mcoo/OPQBot
PKGNAME2=github.com/mcoo/OPQBot/qzone
go get $PKGNAME
go get $PKGNAME2
gopy build -output=bindings_all -vm=python3 $PKGNAME $PKGNAME2
```

**Comment by James4Ever0** [comment]
但是还是不清楚go里面怎么用

**Comment by James4Ever0** [comment]
这样是过不了编译的

```go
import (
	"fmt"
	"github.com/mcoo/OPQBot"
        "github.com/mcoo/OPQBot/qzone"
)
```

**Comment by James4Ever0** [comment]
提取qzone token的正则好像不管用了

**Comment by James4Ever0** [comment]
网页不再返回这个token 不知道跑到什么地方去了

```html
<script type="text/javascript">
    window.g_qzonetoken = ;
    //seajs,qzfl加载失败
    if(!window.seajs) {
        log('seajsLoadFail');
    }
    if(!window.QZFL) {
        log('qzflLoadFail');
    }
</script>
```

**Comment by James4Ever0** [comment]
cookie需要pt4_token p_skey 扫码可以得到

**Comment by RockChinQ** [comment]
> 网页不再返回这个token 不知道跑到什么地方去了
> 
> ```
> <script type="text/javascript">
>     window.g_qzonetoken = ;
>     //seajs,qzfl加载失败
>     if(!window.seajs) {
>         log('seajsLoadFail');
>     }
>     if(!window.QZFL) {
>         log('qzflLoadFail');
>     }
> </script>
> ```

经测试，qzone相关操作现已不再需要qzone_token，获取qzone_token的方式现已被废弃
目前可以到我的仓库https://github.com/RockChinQ/OpenCamwall 中的QQ空间操作模块https://github.com/RockChinQ/OpenCamwall/blob/master/pkg/qzone/model.py   查看相关接口调用方式

**Comment by mcoo** [comment]
如果你想使用 python 编写 OPQBot 的插件请使用 [botoy](https://github.com/opq-osc/botoy)
qzone相关的功能待更新，如果你有时间欢迎提交pr

**Comment by RockChinQ** [comment]
此仓库的发表说说接口调用方式已更新 见 #22

**Comment by guohuiyuan** [comment]
https://github.com/FloatTech/AnimeAPI/tree/main/qzone 重写了，可以参考一下

**Comment by mcoo** [comment]
> https://github.com/FloatTech/AnimeAPI/tree/main/qzone 重写了，可以参考一下

好的，请注意保护下自己的cookie
https://github.com/FloatTech/AnimeAPI/blob/4a200d6330d5cb0983577650cbbafb6b7362b299/qzone/api_test.go#L14

**Comment by guohuiyuan** [comment]
不慌，小号的cookie
&nbsp;
------------------

开心
***@***.***



&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Enjoy"; 
Sendtime: Saturday, Nov 12, 2022 8:40 PM
To: "opq-osc/OPQBot"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [opq-osc/OPQBot] 怎么用这个qzone包呢 (Issue #21)





  
https://github.com/FloatTech/AnimeAPI/tree/main/qzone 重写了，可以参考一下
  
好的，请注意保护下自己的cookie
 https://github.com/FloatTech/AnimeAPI/blob/4a200d6330d5cb0983577650cbbafb6b7362b299/qzone/api_test.go#L14
